name: Release
on:
  release:
    types: [published]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3

      - name: "Publish Features"
        uses: devcontainers/action@v1
        with:
          publish-features: "true"
          base-path-to-templates: "./src"
          devcontainer-cli-version: "0.76.0"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
